// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-dark-factory-agent/pkg"
)

type ClaudeProber struct {
	ProbeStub        func(context.Context) error
	probeMutex       sync.RWMutex
	probeArgsForCall []ClaudeProberProbeArgs
	probeReturns     struct {
		result1 error
	}
	probeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// ClaudeProberProbeArgs holds the arguments of one call to Probe.
type ClaudeProberProbeArgs struct {
	Arg1 context.Context
}

func (fake *ClaudeProber) Probe(arg1 context.Context) error {
	fake.probeMutex.Lock()
	ret, specificReturn := fake.probeReturnsOnCall[len(fake.probeArgsForCall)]
	fake.probeArgsForCall = append(fake.probeArgsForCall, ClaudeProberProbeArgs{arg1})
	stub := fake.ProbeStub
	fakeReturns := fake.probeReturns
	fake.recordInvocation("Probe", []interface{}{arg1})
	fake.probeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ClaudeProber) ProbeCallCount() int {
	fake.probeMutex.RLock()
	defer fake.probeMutex.RUnlock()
	return len(fake.probeArgsForCall)
}

func (fake *ClaudeProber) ProbeCalls(stub func(context.Context) error) {
	fake.probeMutex.Lock()
	defer fake.probeMutex.Unlock()
	fake.ProbeStub = stub
}

func (fake *ClaudeProber) ProbeArgsForCall(i int) context.Context {
	fake.probeMutex.RLock()
	defer fake.probeMutex.RUnlock()
	argsForCall := fake.probeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *ClaudeProber) ProbeArgs() []ClaudeProberProbeArgs {
	fake.probeMutex.RLock()
	defer fake.probeMutex.RUnlock()
	args := make([]ClaudeProberProbeArgs, len(fake.probeArgsForCall))
	copy(args, fake.probeArgsForCall)
	return args
}

func (fake *ClaudeProber) ProbeReturns(result1 error) {
	fake.probeMutex.Lock()
	defer fake.probeMutex.Unlock()
	fake.ProbeStub = nil
	fake.probeReturns = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeProber) ProbeReturnsOnCall(i int, result1 error) {
	fake.probeMutex.Lock()
	defer fake.probeMutex.Unlock()
	fake.ProbeStub = nil
	if fake.probeReturnsOnCall == nil {
		fake.probeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.probeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeProber) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudeProber) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *ClaudeProber) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ClaudeProber = new(ClaudeProber)
