// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/claude"
)

type ClaudeRunner struct {
	RunStub        func(context.Context, string) (*claude.ClaudeResult, error)
	runMutex       sync.RWMutex
	runArgsForCall []ClaudeRunnerRunArgs
	runReturns     struct {
		result1 *claude.ClaudeResult
		result2 error
	}
	runReturnsOnCall map[int]struct {
		result1 *claude.ClaudeResult
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// ClaudeRunnerRunArgs holds the arguments of one call to Run.
type ClaudeRunnerRunArgs struct {
	Arg1 context.Context
	Arg2 string
}

func (fake *ClaudeRunner) Run(arg1 context.Context, arg2 string) (*claude.ClaudeResult, error) {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, ClaudeRunnerRunArgs{arg1, arg2})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ClaudeRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *ClaudeRunner) RunCalls(stub func(context.Context, string) (*claude.ClaudeResult, error)) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *ClaudeRunner) RunArgsForCall(i int) (context.Context, string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *ClaudeRunner) RunArgs() []ClaudeRunnerRunArgs {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	args := make([]ClaudeRunnerRunArgs, len(fake.runArgsForCall))
	copy(args, fake.runArgsForCall)
	return args
}

func (fake *ClaudeRunner) RunReturns(result1 *claude.ClaudeResult, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 *claude.ClaudeResult
		result2 error
	}{result1, result2}
}

func (fake *ClaudeRunner) RunReturnsOnCall(i int, result1 *claude.ClaudeResult, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 *claude.ClaudeResult
			result2 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 *claude.ClaudeResult
		result2 error
	}{result1, result2}
}

func (fake *ClaudeRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudeRunner) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *ClaudeRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claude.ClaudeRunner = new(ClaudeRunner)
