// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-dark-factory-agent/pkg"
)

type ExecutionRunner struct {
	CommitSpecChangesStub        func(context.Context, string) error
	commitSpecChangesMutex       sync.RWMutex
	commitSpecChangesArgsForCall []ExecutionRunnerCommitSpecChangesArgs
	commitSpecChangesReturns     struct {
		result1 error
	}
	commitSpecChangesReturnsOnCall map[int]struct {
		result1 error
	}
	CompleteSpecStub        func(context.Context, string, string) error
	completeSpecMutex       sync.RWMutex
	completeSpecArgsForCall []ExecutionRunnerCompleteSpecArgs
	completeSpecReturns     struct {
		result1 error
	}
	completeSpecReturnsOnCall map[int]struct {
		result1 error
	}
	PushBranchStub        func(context.Context, string, string) error
	pushBranchMutex       sync.RWMutex
	pushBranchArgsForCall []ExecutionRunnerPushBranchArgs
	pushBranchReturns     struct {
		result1 error
	}
	pushBranchReturnsOnCall map[int]struct {
		result1 error
	}
	RunLifecycleStub        func(context.Context, string, []string, []string) (*pkg.LifecycleResult, error)
	runLifecycleMutex       sync.RWMutex
	runLifecycleArgsForCall []ExecutionRunnerRunLifecycleArgs
	runLifecycleReturns     struct {
		result1 *pkg.LifecycleResult
		result2 error
	}
	runLifecycleReturnsOnCall map[int]struct {
		result1 *pkg.LifecycleResult
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// ExecutionRunnerCommitSpecChangesArgs holds the arguments of one call to CommitSpecChanges.
type ExecutionRunnerCommitSpecChangesArgs struct {
	Arg1 context.Context
	Arg2 string
}

// ExecutionRunnerCompleteSpecArgs holds the arguments of one call to CompleteSpec.
type ExecutionRunnerCompleteSpecArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

// ExecutionRunnerPushBranchArgs holds the arguments of one call to PushBranch.
type ExecutionRunnerPushBranchArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

// ExecutionRunnerRunLifecycleArgs holds the arguments of one call to RunLifecycle.
type ExecutionRunnerRunLifecycleArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 []string
	Arg4 []string
}

func (fake *ExecutionRunner) CommitSpecChanges(arg1 context.Context, arg2 string) error {
	fake.commitSpecChangesMutex.Lock()
	ret, specificReturn := fake.commitSpecChangesReturnsOnCall[len(fake.commitSpecChangesArgsForCall)]
	fake.commitSpecChangesArgsForCall = append(fake.commitSpecChangesArgsForCall, ExecutionRunnerCommitSpecChangesArgs{arg1, arg2})
	stub := fake.CommitSpecChangesStub
	fakeReturns := fake.commitSpecChangesReturns
	fake.recordInvocation("CommitSpecChanges", []interface{}{arg1, arg2})
	fake.commitSpecChangesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ExecutionRunner) CommitSpecChangesCallCount() int {
	fake.commitSpecChangesMutex.RLock()
	defer fake.commitSpecChangesMutex.RUnlock()
	return len(fake.commitSpecChangesArgsForCall)
}

func (fake *ExecutionRunner) CommitSpecChangesCalls(stub func(context.Context, string) error) {
	fake.commitSpecChangesMutex.Lock()
	defer fake.commitSpecChangesMutex.Unlock()
	fake.CommitSpecChangesStub = stub
}

func (fake *ExecutionRunner) CommitSpecChangesArgsForCall(i int) (context.Context, string) {
	fake.commitSpecChangesMutex.RLock()
	defer fake.commitSpecChangesMutex.RUnlock()
	argsForCall := fake.commitSpecChangesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *ExecutionRunner) CommitSpecChangesArgs() []ExecutionRunnerCommitSpecChangesArgs {
	fake.commitSpecChangesMutex.RLock()
	defer fake.commitSpecChangesMutex.RUnlock()
	args := make([]ExecutionRunnerCommitSpecChangesArgs, len(fake.commitSpecChangesArgsForCall))
	copy(args, fake.commitSpecChangesArgsForCall)
	return args
}

func (fake *ExecutionRunner) CommitSpecChangesReturns(result1 error) {
	fake.commitSpecChangesMutex.Lock()
	defer fake.commitSpecChangesMutex.Unlock()
	fake.CommitSpecChangesStub = nil
	fake.commitSpecChangesReturns = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) CommitSpecChangesReturnsOnCall(i int, result1 error) {
	fake.commitSpecChangesMutex.Lock()
	defer fake.commitSpecChangesMutex.Unlock()
	fake.CommitSpecChangesStub = nil
	if fake.commitSpecChangesReturnsOnCall == nil {
		fake.commitSpecChangesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitSpecChangesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) CompleteSpec(arg1 context.Context, arg2 string, arg3 string) error {
	fake.completeSpecMutex.Lock()
	ret, specificReturn := fake.completeSpecReturnsOnCall[len(fake.completeSpecArgsForCall)]
	fake.completeSpecArgsForCall = append(fake.completeSpecArgsForCall, ExecutionRunnerCompleteSpecArgs{arg1, arg2, arg3})
	stub := fake.CompleteSpecStub
	fakeReturns := fake.completeSpecReturns
	fake.recordInvocation("CompleteSpec", []interface{}{arg1, arg2, arg3})
	fake.completeSpecMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ExecutionRunner) CompleteSpecCallCount() int {
	fake.completeSpecMutex.RLock()
	defer fake.completeSpecMutex.RUnlock()
	return len(fake.completeSpecArgsForCall)
}

func (fake *ExecutionRunner) CompleteSpecCalls(stub func(context.Context, string, string) error) {
	fake.completeSpecMutex.Lock()
	defer fake.completeSpecMutex.Unlock()
	fake.CompleteSpecStub = stub
}

func (fake *ExecutionRunner) CompleteSpecArgsForCall(i int) (context.Context, string, string) {
	fake.completeSpecMutex.RLock()
	defer fake.completeSpecMutex.RUnlock()
	argsForCall := fake.completeSpecArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *ExecutionRunner) CompleteSpecArgs() []ExecutionRunnerCompleteSpecArgs {
	fake.completeSpecMutex.RLock()
	defer fake.completeSpecMutex.RUnlock()
	args := make([]ExecutionRunnerCompleteSpecArgs, len(fake.completeSpecArgsForCall))
	copy(args, fake.completeSpecArgsForCall)
	return args
}

func (fake *ExecutionRunner) CompleteSpecReturns(result1 error) {
	fake.completeSpecMutex.Lock()
	defer fake.completeSpecMutex.Unlock()
	fake.CompleteSpecStub = nil
	fake.completeSpecReturns = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) CompleteSpecReturnsOnCall(i int, result1 error) {
	fake.completeSpecMutex.Lock()
	defer fake.completeSpecMutex.Unlock()
	fake.CompleteSpecStub = nil
	if fake.completeSpecReturnsOnCall == nil {
		fake.completeSpecReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.completeSpecReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) PushBranch(arg1 context.Context, arg2 string, arg3 string) error {
	fake.pushBranchMutex.Lock()
	ret, specificReturn := fake.pushBranchReturnsOnCall[len(fake.pushBranchArgsForCall)]
	fake.pushBranchArgsForCall = append(fake.pushBranchArgsForCall, ExecutionRunnerPushBranchArgs{arg1, arg2, arg3})
	stub := fake.PushBranchStub
	fakeReturns := fake.pushBranchReturns
	fake.recordInvocation("PushBranch", []interface{}{arg1, arg2, arg3})
	fake.pushBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ExecutionRunner) PushBranchCallCount() int {
	fake.pushBranchMutex.RLock()
	defer fake.pushBranchMutex.RUnlock()
	return len(fake.pushBranchArgsForCall)
}

func (fake *ExecutionRunner) PushBranchCalls(stub func(context.Context, string, string) error) {
	fake.pushBranchMutex.Lock()
	defer fake.pushBranchMutex.Unlock()
	fake.PushBranchStub = stub
}

func (fake *ExecutionRunner) PushBranchArgsForCall(i int) (context.Context, string, string) {
	fake.pushBranchMutex.RLock()
	defer fake.pushBranchMutex.RUnlock()
	argsForCall := fake.pushBranchArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *ExecutionRunner) PushBranchArgs() []ExecutionRunnerPushBranchArgs {
	fake.pushBranchMutex.RLock()
	defer fake.pushBranchMutex.RUnlock()
	args := make([]ExecutionRunnerPushBranchArgs, len(fake.pushBranchArgsForCall))
	copy(args, fake.pushBranchArgsForCall)
	return args
}

func (fake *ExecutionRunner) PushBranchReturns(result1 error) {
	fake.pushBranchMutex.Lock()
	defer fake.pushBranchMutex.Unlock()
	fake.PushBranchStub = nil
	fake.pushBranchReturns = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) PushBranchReturnsOnCall(i int, result1 error) {
	fake.pushBranchMutex.Lock()
	defer fake.pushBranchMutex.Unlock()
	fake.PushBranchStub = nil
	if fake.pushBranchReturnsOnCall == nil {
		fake.pushBranchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushBranchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ExecutionRunner) RunLifecycle(arg1 context.Context, arg2 string, arg3 []string, arg4 []string) (*pkg.LifecycleResult, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.runLifecycleMutex.Lock()
	ret, specificReturn := fake.runLifecycleReturnsOnCall[len(fake.runLifecycleArgsForCall)]
	fake.runLifecycleArgsForCall = append(fake.runLifecycleArgsForCall, ExecutionRunnerRunLifecycleArgs{arg1, arg2, arg3Copy, arg4Copy})
	stub := fake.RunLifecycleStub
	fakeReturns := fake.runLifecycleReturns
	fake.recordInvocation("RunLifecycle", []interface{}{arg1, arg2, arg3Copy, arg4Copy})
	fake.runLifecycleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ExecutionRunner) RunLifecycleCallCount() int {
	fake.runLifecycleMutex.RLock()
	defer fake.runLifecycleMutex.RUnlock()
	return len(fake.runLifecycleArgsForCall)
}

func (fake *ExecutionRunner) RunLifecycleCalls(stub func(context.Context, string, []string, []string) (*pkg.LifecycleResult, error)) {
	fake.runLifecycleMutex.Lock()
	defer fake.runLifecycleMutex.Unlock()
	fake.RunLifecycleStub = stub
}

func (fake *ExecutionRunner) RunLifecycleArgsForCall(i int) (context.Context, string, []string, []string) {
	fake.runLifecycleMutex.RLock()
	defer fake.runLifecycleMutex.RUnlock()
	argsForCall := fake.runLifecycleArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *ExecutionRunner) RunLifecycleArgs() []ExecutionRunnerRunLifecycleArgs {
	fake.runLifecycleMutex.RLock()
	defer fake.runLifecycleMutex.RUnlock()
	args := make([]ExecutionRunnerRunLifecycleArgs, len(fake.runLifecycleArgsForCall))
	copy(args, fake.runLifecycleArgsForCall)
	return args
}

func (fake *ExecutionRunner) RunLifecycleReturns(result1 *pkg.LifecycleResult, result2 error) {
	fake.runLifecycleMutex.Lock()
	defer fake.runLifecycleMutex.Unlock()
	fake.RunLifecycleStub = nil
	fake.runLifecycleReturns = struct {
		result1 *pkg.LifecycleResult
		result2 error
	}{result1, result2}
}

func (fake *ExecutionRunner) RunLifecycleReturnsOnCall(i int, result1 *pkg.LifecycleResult, result2 error) {
	fake.runLifecycleMutex.Lock()
	defer fake.runLifecycleMutex.Unlock()
	fake.RunLifecycleStub = nil
	if fake.runLifecycleReturnsOnCall == nil {
		fake.runLifecycleReturnsOnCall = make(map[int]struct {
			result1 *pkg.LifecycleResult
			result2 error
		})
	}
	fake.runLifecycleReturnsOnCall[i] = struct {
		result1 *pkg.LifecycleResult
		result2 error
	}{result1, result2}
}

func (fake *ExecutionRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ExecutionRunner) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *ExecutionRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ExecutionRunner = new(ExecutionRunner)
