// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-dark-factory-agent/pkg"
)

type GitHubClient struct {
	GetPullRequestStub        func(context.Context, string, string, int) (*pkg.PullRequestInfo, error)
	getPullRequestMutex       sync.RWMutex
	getPullRequestArgsForCall []GitHubClientGetPullRequestArgs
	getPullRequestReturns     struct {
		result1 *pkg.PullRequestInfo
		result2 error
	}
	getPullRequestReturnsOnCall map[int]struct {
		result1 *pkg.PullRequestInfo
		result2 error
	}
	ListPullRequestFilesStub        func(context.Context, string, string, int) ([]string, error)
	listPullRequestFilesMutex       sync.RWMutex
	listPullRequestFilesArgsForCall []GitHubClientListPullRequestFilesArgs
	listPullRequestFilesReturns     struct {
		result1 []string
		result2 error
	}
	listPullRequestFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// GitHubClientGetPullRequestArgs holds the arguments of one call to GetPullRequest.
type GitHubClientGetPullRequestArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
	Arg4 int
}

// GitHubClientListPullRequestFilesArgs holds the arguments of one call to ListPullRequestFiles.
type GitHubClientListPullRequestFilesArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
	Arg4 int
}

func (fake *GitHubClient) GetPullRequest(arg1 context.Context, arg2 string, arg3 string, arg4 int) (*pkg.PullRequestInfo, error) {
	fake.getPullRequestMutex.Lock()
	ret, specificReturn := fake.getPullRequestReturnsOnCall[len(fake.getPullRequestArgsForCall)]
	fake.getPullRequestArgsForCall = append(fake.getPullRequestArgsForCall, GitHubClientGetPullRequestArgs{arg1, arg2, arg3, arg4})
	stub := fake.GetPullRequestStub
	fakeReturns := fake.getPullRequestReturns
	fake.recordInvocation("GetPullRequest", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPullRequestCallCount() int {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	return len(fake.getPullRequestArgsForCall)
}

func (fake *GitHubClient) GetPullRequestCalls(stub func(context.Context, string, string, int) (*pkg.PullRequestInfo, error)) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = stub
}

func (fake *GitHubClient) GetPullRequestArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	argsForCall := fake.getPullRequestArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *GitHubClient) GetPullRequestArgs() []GitHubClientGetPullRequestArgs {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	args := make([]GitHubClientGetPullRequestArgs, len(fake.getPullRequestArgsForCall))
	copy(args, fake.getPullRequestArgsForCall)
	return args
}

func (fake *GitHubClient) GetPullRequestReturns(result1 *pkg.PullRequestInfo, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	fake.getPullRequestReturns = struct {
		result1 *pkg.PullRequestInfo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPullRequestReturnsOnCall(i int, result1 *pkg.PullRequestInfo, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	if fake.getPullRequestReturnsOnCall == nil {
		fake.getPullRequestReturnsOnCall = make(map[int]struct {
			result1 *pkg.PullRequestInfo
			result2 error
		})
	}
	fake.getPullRequestReturnsOnCall[i] = struct {
		result1 *pkg.PullRequestInfo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPullRequestFiles(arg1 context.Context, arg2 string, arg3 string, arg4 int) ([]string, error) {
	fake.listPullRequestFilesMutex.Lock()
	ret, specificReturn := fake.listPullRequestFilesReturnsOnCall[len(fake.listPullRequestFilesArgsForCall)]
	fake.listPullRequestFilesArgsForCall = append(fake.listPullRequestFilesArgsForCall, GitHubClientListPullRequestFilesArgs{arg1, arg2, arg3, arg4})
	stub := fake.ListPullRequestFilesStub
	fakeReturns := fake.listPullRequestFilesReturns
	fake.recordInvocation("ListPullRequestFiles", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPullRequestFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListPullRequestFilesCallCount() int {
	fake.listPullRequestFilesMutex.RLock()
	defer fake.listPullRequestFilesMutex.RUnlock()
	return len(fake.listPullRequestFilesArgsForCall)
}

func (fake *GitHubClient) ListPullRequestFilesCalls(stub func(context.Context, string, string, int) ([]string, error)) {
	fake.listPullRequestFilesMutex.Lock()
	defer fake.listPullRequestFilesMutex.Unlock()
	fake.ListPullRequestFilesStub = stub
}

func (fake *GitHubClient) ListPullRequestFilesArgsForCall(i int) (context.Context, string, string, int) {
	fake.listPullRequestFilesMutex.RLock()
	defer fake.listPullRequestFilesMutex.RUnlock()
	argsForCall := fake.listPullRequestFilesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *GitHubClient) ListPullRequestFilesArgs() []GitHubClientListPullRequestFilesArgs {
	fake.listPullRequestFilesMutex.RLock()
	defer fake.listPullRequestFilesMutex.RUnlock()
	args := make([]GitHubClientListPullRequestFilesArgs, len(fake.listPullRequestFilesArgsForCall))
	copy(args, fake.listPullRequestFilesArgsForCall)
	return args
}

func (fake *GitHubClient) ListPullRequestFilesReturns(result1 []string, result2 error) {
	fake.listPullRequestFilesMutex.Lock()
	defer fake.listPullRequestFilesMutex.Unlock()
	fake.ListPullRequestFilesStub = nil
	fake.listPullRequestFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPullRequestFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listPullRequestFilesMutex.Lock()
	defer fake.listPullRequestFilesMutex.Unlock()
	fake.ListPullRequestFilesStub = nil
	if fake.listPullRequestFilesReturnsOnCall == nil {
		fake.listPullRequestFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listPullRequestFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
